# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from typing import List, Callable, Optional

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient
from spacetimedb_sdk.spacetimedb_client import ReducerEvent


reducer_name = "send_message"

def send_message(text: str, then: Optional[Callable[["ReducerEvent"], None]] = None):
	SpacetimeDBClient.instance._reducer_call("send_message", text, then=then)

def _decode_args(data):
	return [str(data[0])]
