# THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
# WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

from __future__ import annotations
from typing import List, Iterator, Callable

from spacetimedb_sdk.spacetimedb_client import SpacetimeDBClient, ReducerEvent


class SystemNotification:
	"""Event table: rows are ephemeral and never stored in the local cache.

	The server publishes a SystemNotification row whenever a significant
	system-level event occurs (e.g. server restart warning, maintenance
	notice). Clients receive row-update callbacks for each notification but
	the rows are not retained between updates.
	"""

	is_table_class = True
	is_event_table = True  # ephemeral — callbacks fire but rows are not cached

	@classmethod
	def register_row_update(cls, callback: Callable[[str, "SystemNotification", "SystemNotification", ReducerEvent], None]):
		SpacetimeDBClient.instance._register_row_update("SystemNotification", callback)

	def __init__(self, data: List[object]):
		self.data = {}
		self.data["level"] = str(data[0])    # e.g. "info", "warning", "error"
		self.data["message"] = str(data[1])

	def __getattr__(self, name: str):
		return self.data.get(name)
